# Generated by Django 4.2.4 on 2023-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
